# Generated by Django 2.2.1 on 2019-06-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20190611_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
