# Generated by Django 2.2.1 on 2019-06-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_auto_20190611_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FequenciaEvento',
            new_name='FrequenciaEvento',
        ),
    ]
