# Generated by Django 2.2.1 on 2019-06-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_auto_20190611_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='tempo_no_brasil',
            new_name='data_de_entrada_no_brasil',
        ),
    ]
