# Generated by Django 2.2.1 on 2019-06-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_remove_pessoa_cedula_identificacao_conjuge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjugues',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.Empresa'),
        ),
    ]
