# Generated by Django 2.2.2 on 2019-06-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_auto_20190613_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Público'),
        ),
        migrations.AlterField(
            model_name='conjugues',
            name='cedula_indentificacao',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Cédula de indentificacao'),
        ),
        migrations.AlterField(
            model_name='conjugues',
            name='cpf',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='conjugues',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='conjugues',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissão'),
        ),
        migrations.AlterField(
            model_name='conjugues',
            name='n_carteira_trabalho',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Número da carteira de trabalho'),
        ),
        migrations.AlterField(
            model_name='conjugues',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Orgão expedidor'),
        ),
        migrations.AlterField(
            model_name='conjugues',
            name='trabalha',
            field=models.BooleanField(default=False, verbose_name='Trabalha com carteira assinada'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.Ufs', verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cedula_indentificacao',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Cédula de indentificação'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissão'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='n_carteira_trabalho',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Número da carteira de trabalho'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Orgão expedidor'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='profissao',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='profissão'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='trabalha',
            field=models.BooleanField(default=False, verbose_name='Trabalha com carteira assinada'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.Ufs', verbose_name='UF'),
        ),
        migrations.CreateModel(
            name='FrequenciaEventoPublico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pessoa', models.CharField(max_length=240)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.Evento')),
            ],
        ),
    ]
