# Generated by Django 2.2.2 on 2019-06-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_auto_20190620_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='status',
            new_name='ativo',
        ),
    ]
