# Generated by Django 2.2.2 on 2019-06-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_auto_20190620_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
